name: "Lint"

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  unit-test:
    name: Perform checks
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (audit mode)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout the code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle and cache
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2
        with:
          gradle-version: wrapper

      - name: Run checks
        run: ./gradlew lint

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@3c3833e0f8c1c83d449a7478aa59c036a9165498 # v3.29.5
        if: success() || failure()
        with:
          sarif_file: /home/runner/work/StreetComplete/StreetComplete/app/build/reports/lint-results-debug.sarif
          category: lint
